### ISSUE TITLE
After starting it says always, Code update Available 

### ISSUE THREAD

**Issue by uwerichter** [DataJuggler/DataTier.Net#19] opened 2019-10-25 15:56 UTC
and SQL Update available.
But i'am pretty sure that i just installed the latest version, a few minutes ago.

**Comment by DataJuggler** [comment] 2019-11-22 22:28
I just saw this message, sorry for the long delay. The code is supposed to update your database, but if the connection string hasn't been set (?) it doesn't appear to work right.

Until I get a fix, in MainForm.cs (located in the Client\Forms folder) around line 2100 is the code of CheckForUpdate. You can comment out the check for update code and I will work on getting to not show this when a connection isn't available (that is my guess).

Again sorry, I came here to create an issue and noticed there were 2 issues.

**Comment by DataJuggler** [comment] 2019-11-22 22:50
Are you sure this is still an issue? I just looked at the code and Database Connection has to pass before the check for update, so my theory above is not applicable.

Thanks, and my email is listed on my Git Hub contact info if you still need help.

**Comment by DataJuggler** [comment] 2020-01-09 21:47
I am closing this issue as I believe this was caused by a Nuget package changed for cryptography around the time you created this issue.

You can always turn off Check For Updates by unchecking the box on the mian form.

If the issue happens again after getting the latest version, please contact me.

**Closed by DataJuggler** 2020-01-09 21:47 UTC
